[package]
name = "influenceoverfueler"
version = "0.1.0"

[dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry", tag = "v0.12.0" }
starknet = "2.5.4"

[[target.starknet-contract]]
casm = true